language: node_js
node_js: node
cache: npm
jobs:
  include:
    - stage: Test
      install: npm ci
      before_script: npm run build
      script:
        - npm run test
        - npm run size
    - stage: Release
      if: tag =~ ^v[0-9]
      install: npm ci
      before_script: npm run build
      script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - node scripts/publish.js
