name: release
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'remix-run/history'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test & npm run size

      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          node scripts/publish.js